changelog:
  exclude:
    labels:
      - ignore-for-release
    authors:
      - octocat
  categories:
    - title: Mudanças Importantes 🛠
      labels:
        - Semver-Major
        - breaking-change
    - title: Novas Funcionalidades 🎉
      labels:
        - Semver-Minor
        - enhancement
    - title: Outras Mudanças
      labels:
        - "*"
