name: Portifolio de Documentação
on:
  schedule:
    - cron: '0 22 * * *' # Executar todos os dias às 22:00 UTC
  push:
    branches:
      - main 

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Verificar código fonte
      uses: actions/checkout@v4

    - name: Instalar Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.23'  # Defina a versão do Go que você está usando

    - name: Instalar dependências (se necessário)
      run: go mod tidy

    - name: Executar o script de geração do changelog e deploy
      run: go run main.go
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
